### ISSUE TITLE
RSS autodiscovery

### ISSUE THREAD

**Issue by danirod** [Chemaclass/chemaclass.com#2]
There is a feed at https://chemaclass.com/atom.xml, but there are no indications on how to reach it.

If there is a <link> tag in the <head> with the proper attributes, it is possible to just add `https://chemaclass.com` to a feed reader and it will find the <link> tag in the page to know where is the actual feed URL.

The following diff seems to do the trick but I haven't ever used Zola and it somehow scares me to propose it via PR:

```diff
diff --git a/templates/base.html b/templates/base.html
index 1d6807c..2dad865 100644
--- a/templates/base.html
+++ b/templates/base.html
@@ -122,6 +122,9 @@
       <link rel="stylesheet" href="{{ get_url(path='main.css') | safe }}">
       <link rel="stylesheet" href="{{ get_url(path='custom.css') | safe }}">
     {% endblock styles %}
+    {% block rss %}
+      <link rel="alternate" type="application/atom+xml" href="{{ get_url(path='atom.xml') | safe }}" title="Atom Feed">
+    {% endblock rss %}
     {% block posthead %}{% endblock posthead %}
   </head>
   <body>
```

**Comment by Chemaclass** [comment]
Thanks a lot for the suggestion! Actually, don't be afraid of creating PRs, even if you're not 100% sure, it might be a place for discussion, like this issue. And before merging it someone (at least me) will test it for sure.

So, once you have fork/clone the repo, and installed zola, you can test it yourself locally with running "zola serve" in the root of the project. Let me know if this worked out for you, @danirod
