### ISSUE TITLE
Button to scroll to the top

### ISSUE THREAD

**Issue by Chemaclass** [Chemaclass/chemaclass.com#22]
Some posts are large enough that going to the top requires scrolling up multiple times. 

I would like to have a button on the right bottom corner (with an arrow or similar) that will move the user to the top of the page

**Comment by AvulaRamSwaroop** [comment]
Can you assign me this?

**Comment by Chemaclass** [comment]
@AvulaRamSwaroop feel free to create a PR if this was not done
